"""empty message

Revision ID: 8656e762d81c
Revises: 
Create Date: 2023-02-24 10:05:29.025438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8656e762d81c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('class',
    sa.Column('class_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('class_detail', sa.String(length=150), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('class_id'),
    sa.UniqueConstraint('class_name')
    )
    op.create_table('lesson',
    sa.Column('lesson_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_name', sa.String(length=100), nullable=False),
    sa.Column('lesson_detail', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('lesson_id'),
    sa.UniqueConstraint('lesson_name')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_position', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_position')
    )
    op.create_table('school',
    sa.Column('school_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_code', sa.String(length=100), nullable=False),
    sa.Column('school_name', sa.String(length=100), nullable=False),
    sa.Column('school_address', sa.String(length=100), nullable=True),
    sa.Column('school_phone', sa.String(length=11), nullable=True),
    sa.Column('school_boss', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('school_id'),
    sa.UniqueConstraint('school_code')
    )
    op.create_table('subject',
    sa.Column('subject_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('subject_detail', sa.String(length=150), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('subject_name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('subject')
    op.drop_table('school')
    op.drop_table('role')
    op.drop_table('lesson')
    op.drop_table('class')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
